# Generated by Django 5.1.5 on 2025-02-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Student',
        ),
    ]
