# Generated by Django 5.1.5 on 2025-02-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_rename_teacher_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('students', models.ManyToManyField(related_name='courses', to='students.student')),
            ],
        ),
    ]
